### ISSUE TITLE
wallpaper does not zoom to fit screen

### ISSUE THREAD

**Issue by rubybirdy** [ghostlexly/gpu-video-wallpaper#17]
using a wallpaper without a resolution matching that of the monitor results in large black bars appearing instead of simply zooming in the wallpaper. this could be a problem for setups with multiple monitors of differing resolutions

![image](https://user-images.githubusercontent.com/79671269/155415594-c186068c-a954-47a1-ad1f-d4889d8e1c89.png)

**Comment by ghostlexly** [comment]
Which dimensions are your wallpaper and desktop screen ?

**Comment by rubybirdy** [comment]
my wallpaper is 2560x1080, and my monitor is 1920x1080

**Comment by SwallowYourDreams** [comment]
video-wallpaper does not support stretch or zoom to fit screen yet. For now, it just takes the video you throw at it and displays it as is. If your screen resolution deviates from video resolution, mpv will add black bars.

For now, the only workaround is to change the video resolution size to fit screen size, i.e. in your case: cut the width to 1920px. This shouldn't be a problem because your video wallpaper was artificially extended in width (hence the two ferris wheels, trees, falling stars, etc.).

We might consider adding a zoom/stretch video to match screen resolution feature in the future.
